### ISSUE TITLE
NameError: name 'plen' is not defined in preprocessed_dataset.py

### ISSUE THREAD

**Issue by ghost** [Njk-901aru/multi_DTI#1]
Hi 

I was trying to run the dataset_easy example and it seems like in the preprocessed_dataset.py line 74:
onehot_tr = np.empty((plen, Max, 20), dtype='float32')

plen is not defined anywhere else in the code?

and the following line has integer_encoded_tr which is not defined too.

pls advise!

Thank you and look forward to your reply!

**Comment by Njk-901aru** [comment]
Hi

"plen" means the length of "pID" in the preprocessed_dataset.py.

And "integer_encoded_tr" is same as "integer_encoded" defined at line 68-70. 

I'll correct the code later.

Thank you for your notification!

**Comment by Njk-901aru** [comment]
Hi

"plen" means the length of "pID" in the preprocessed_dataset.py.

And "integer_encoded_tr" is same as "integer_encoded" defined at line 68-70. 

I'll correct the code later.

Thank you for your notification!

**Comment by ghost** [comment]
Thanks for the correction!

Some other issues i noticed:

For preprocessing.py

   1. from rdkit.Chem import AllChem should be added
   2. np.save(args.input+'/cv_'+str(i)+args.data+'_reprotein.npy', onehot_tr)
   instead of ontr

For training.py

   1. http://www.dna.bio.keio.ac.jp/smiles/SCFPfunctions.py needs to be
   added
   2. cupy is not used? can be commented out?
   3. from feature import * - not sure which package feature is from or can
   be commented out

For integrateMV.py

   1. conv1_chem=L.Convolution2D(1, p1, (k1, clensize), stride=s1, pad =
   (k1//2,0)),     requires p1 (pf1?) and k1 which are not provided

Thank you very much!
